version: '3'
services:
  # Nginx Server
  nginx_server: 
    image: nginx
    container_name: server
    volumes:
      - ./server.conf:/etc/nginx/conf.d/default.conf
      - ../test.txt:/etc/nginx/html/test.txt
      - ./nginx/logs/server/:/var/log/nginx/
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 9080:80
  
  # Nginx proxy
  nginx_proxy: 
    image: nginx
    container_name: proxy
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/proxy/:/var/log/nginx/
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 8080:80
    links:
      - nginx_server
