version: '3'
services:
  # Payara Server
  nginx_server: 
    image: nginx
    container_name: server
    volumes:
      - ./server.conf:/etc/nginx/conf.d/default.conf
      - ./test1:/etc/nginx/html/test2
      - ./test2:/etc/nginx/html/test2
      - ./nginx/logs/server/:/var/log/nginx/
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 9080:8080
  
  # Nginx proxy
  nginx_proxy: 
    image: nginx
    container_name: proxy
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/proxy/:/var/log/nginx/
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 8080:80
    links:
      - payara_server
